### ISSUE TITLE
Add missing trait implementations

### ISSUE THREAD

**Issue by polachok** [polachok/mio-afpacket#4]
impl<'a> Read for &'a RawPacketStream
impl Debug for RawPacketStream
impl IntoRawFd for RawPacketStream
impl AsRawFd for RawPacketStream
impl FromRawFd for RawPacketStream

**Comment by SmilingNavern** [comment]
I will try this one:)

**Comment by SmilingNavern** [comment]
We can close this issue now:) @polachok

**Comment by polachok** [comment]
Thanks!
